//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/common}last-modified-date" minOccurs="0"/>
 *         &lt;element name="educations" type="{http://www.orcid.org/ns/activities}educations" minOccurs="0"/>
 *         &lt;element name="employments" type="{http://www.orcid.org/ns/activities}employments" minOccurs="0"/>
 *         &lt;element name="fundings" type="{http://www.orcid.org/ns/activities}fundings" minOccurs="0"/>
 *         &lt;element name="peer-reviews" type="{http://www.orcid.org/ns/activities}peer-reviews" minOccurs="0"/>
 *         &lt;element name="works" type="{http://www.orcid.org/ns/activities}works" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="path" type="{http://www.orcid.org/ns/common}element-path" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lastModifiedDate",
    "educations",
    "employments",
    "fundings",
    "peerReviews",
    "works"
})
@XmlRootElement(name = "activities-summary", namespace = "http://www.orcid.org/ns/activities")
public class ActivitiesSummary
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "last-modified-date")
    protected LastModifiedDate lastModifiedDate;
    @XmlElement(namespace = "http://www.orcid.org/ns/activities")
    protected Educations educations;
    @XmlElement(namespace = "http://www.orcid.org/ns/activities")
    protected Employments employments;
    @XmlElement(namespace = "http://www.orcid.org/ns/activities")
    protected Fundings fundings;
    @XmlElement(name = "peer-reviews", namespace = "http://www.orcid.org/ns/activities")
    protected PeerReviews peerReviews;
    @XmlElement(namespace = "http://www.orcid.org/ns/activities")
    protected Works works;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link LastModifiedDate }
     *     
     */
    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastModifiedDate }
     *     
     */
    public void setLastModifiedDate(LastModifiedDate value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the educations property.
     * 
     * @return
     *     possible object is
     *     {@link Educations }
     *     
     */
    public Educations getEducations() {
        return educations;
    }

    /**
     * Sets the value of the educations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Educations }
     *     
     */
    public void setEducations(Educations value) {
        this.educations = value;
    }

    /**
     * Gets the value of the employments property.
     * 
     * @return
     *     possible object is
     *     {@link Employments }
     *     
     */
    public Employments getEmployments() {
        return employments;
    }

    /**
     * Sets the value of the employments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employments }
     *     
     */
    public void setEmployments(Employments value) {
        this.employments = value;
    }

    /**
     * Gets the value of the fundings property.
     * 
     * @return
     *     possible object is
     *     {@link Fundings }
     *     
     */
    public Fundings getFundings() {
        return fundings;
    }

    /**
     * Sets the value of the fundings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fundings }
     *     
     */
    public void setFundings(Fundings value) {
        this.fundings = value;
    }

    /**
     * Gets the value of the peerReviews property.
     * 
     * @return
     *     possible object is
     *     {@link PeerReviews }
     *     
     */
    public PeerReviews getPeerReviews() {
        return peerReviews;
    }

    /**
     * Sets the value of the peerReviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeerReviews }
     *     
     */
    public void setPeerReviews(PeerReviews value) {
        this.peerReviews = value;
    }

    /**
     * Gets the value of the works property.
     * 
     * @return
     *     possible object is
     *     {@link Works }
     *     
     */
    public Works getWorks() {
        return works;
    }

    /**
     * Sets the value of the works property.
     * 
     * @param value
     *     allowed object is
     *     {@link Works }
     *     
     */
    public void setWorks(Works value) {
        this.works = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
