//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Container for a work citation. Citations may be
 * 				fielded (e.g., RIS, BibTeX - preferred citation type), or may be
 * 				textual (APA, MLA, Chicago, etc.) The required work-citation-type
 * 				element indicates the format of the citation.
 * 			
 * 
 * <p>Java class for citation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="citation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="citation-type" type="{http://www.orcid.org/ns/work}citation-type"/>
 *         &lt;element name="citation-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "citation", namespace = "http://www.orcid.org/ns/work", propOrder = {
    "citationType",
    "citationValue"
})
public class Citation
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "citation-type", required = true, defaultValue = "formatted-unspecified")
    @XmlSchemaType(name = "string")
    protected CitationType citationType;
    @XmlElement(name = "citation-value", required = true)
    protected String citationValue;

    /**
     * Gets the value of the citationType property.
     * 
     * @return
     *     possible object is
     *     {@link CitationType }
     *     
     */
    public CitationType getCitationType() {
        return citationType;
    }

    /**
     * Sets the value of the citationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationType }
     *     
     */
    public void setCitationType(CitationType value) {
        this.citationType = value;
    }

    /**
     * Gets the value of the citationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitationValue() {
        return citationValue;
    }

    /**
     * Sets the value of the citationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitationValue(String value) {
        this.citationValue = value;
    }

}
