//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contributor-role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contributor-role">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="author"/>
 *     &lt;enumeration value="assignee"/>
 *     &lt;enumeration value="editor"/>
 *     &lt;enumeration value="chair-or-translator"/>
 *     &lt;enumeration value="co-investigator"/>
 *     &lt;enumeration value="co-inventor"/>
 *     &lt;enumeration value="graduate-student"/>
 *     &lt;enumeration value="other-inventor"/>
 *     &lt;enumeration value="principal-investigator"/>
 *     &lt;enumeration value="postdoctoral-researcher"/>
 *     &lt;enumeration value="support-staff"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "contributor-role")
@XmlEnum
public enum ContributorRole {

    @XmlEnumValue("author")
    AUTHOR("author"),
    @XmlEnumValue("assignee")
    ASSIGNEE("assignee"),
    @XmlEnumValue("editor")
    EDITOR("editor"),
    @XmlEnumValue("chair-or-translator")
    CHAIR_OR_TRANSLATOR("chair-or-translator"),
    @XmlEnumValue("co-investigator")
    CO_INVESTIGATOR("co-investigator"),
    @XmlEnumValue("co-inventor")
    CO_INVENTOR("co-inventor"),
    @XmlEnumValue("graduate-student")
    GRADUATE_STUDENT("graduate-student"),
    @XmlEnumValue("other-inventor")
    OTHER_INVENTOR("other-inventor"),
    @XmlEnumValue("principal-investigator")
    PRINCIPAL_INVESTIGATOR("principal-investigator"),
    @XmlEnumValue("postdoctoral-researcher")
    POSTDOCTORAL_RESEARCHER("postdoctoral-researcher"),
    @XmlEnumValue("support-staff")
    SUPPORT_STAFF("support-staff");
    private final String value;

    ContributorRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContributorRole fromValue(String v) {
        for (ContributorRole c: ContributorRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
