//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contributor-role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contributor-role">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="lead"/>
 *     &lt;enumeration value="co-lead"/>
 *     &lt;enumeration value="supported-by"/>
 *     &lt;enumeration value="other-contribution"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "contributor-role", namespace = "http://www.orcid.org/ns/funding")
@XmlEnum
public enum ContributorRole2 {

    @XmlEnumValue("lead")
    LEAD("lead"),
    @XmlEnumValue("co-lead")
    CO_LEAD("co-lead"),
    @XmlEnumValue("supported-by")
    SUPPORTED_BY("supported-by"),
    @XmlEnumValue("other-contribution")
    OTHER_CONTRIBUTION("other-contribution");
    private final String value;

    ContributorRole2(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContributorRole2 fromValue(String v) {
        for (ContributorRole2 c: ContributorRole2 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
