//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A reference to an external identifier, suitable for works, people and funding
 * 
 * <p>Java class for external-id complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="external-id">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.orcid.org/ns/common}element-summary">
 *       &lt;sequence>
 *         &lt;element name="external-id-type" type="{http://www.orcid.org/ns/common}non-empty-string"/>
 *         &lt;element name="external-id-value" type="{http://www.orcid.org/ns/common}non-empty-string"/>
 *         &lt;element name="external-id-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="external-id-relationship" type="{http://www.orcid.org/ns/common}relationship-type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "external-id", propOrder = {
    "externalIdType",
    "externalIdValue",
    "externalIdUrl",
    "externalIdRelationship"
})
@XmlSeeAlso({
    ExternalIdentifier.class
})
public class ExternalId
    extends ElementSummary
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "external-id-type", required = true)
    protected String externalIdType;
    @XmlElement(name = "external-id-value", required = true)
    protected String externalIdValue;
    @XmlElement(name = "external-id-url")
    @XmlSchemaType(name = "anyURI")
    protected String externalIdUrl;
    @XmlElement(name = "external-id-relationship")
    @XmlSchemaType(name = "string")
    protected RelationshipType externalIdRelationship;

    /**
     * Gets the value of the externalIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalIdType() {
        return externalIdType;
    }

    /**
     * Sets the value of the externalIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalIdType(String value) {
        this.externalIdType = value;
    }

    /**
     * Gets the value of the externalIdValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalIdValue() {
        return externalIdValue;
    }

    /**
     * Sets the value of the externalIdValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalIdValue(String value) {
        this.externalIdValue = value;
    }

    /**
     * Gets the value of the externalIdUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalIdUrl() {
        return externalIdUrl;
    }

    /**
     * Sets the value of the externalIdUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalIdUrl(String value) {
        this.externalIdUrl = value;
    }

    /**
     * Gets the value of the externalIdRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipType }
     *     
     */
    public RelationshipType getExternalIdRelationship() {
        return externalIdRelationship;
    }

    /**
     * Sets the value of the externalIdRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipType }
     *     
     */
    public void setExternalIdRelationship(RelationshipType value) {
        this.externalIdRelationship = value;
    }

}
