//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.orcid.org/ns/common}element-summary">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.orcid.org/ns/funding}funding-title"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}external-ids" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.orcid.org/ns/funding}funding-type"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}start-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}end-date" minOccurs="0"/>
 *         &lt;element name="organization" type="{http://www.orcid.org/ns/common}organization"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "externalIds",
    "type",
    "startDate",
    "endDate",
    "organization"
})
@XmlRootElement(name = "funding-summary", namespace = "http://www.orcid.org/ns/funding")
public class FundingSummary
    extends ElementSummary
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://www.orcid.org/ns/funding", required = true)
    protected FundingTitle title;
    @XmlElement(name = "external-ids")
    protected ExternalIds externalIds;
    @XmlElement(namespace = "http://www.orcid.org/ns/funding", required = true)
    @XmlSchemaType(name = "string")
    protected FundingType type;
    @XmlElement(name = "start-date")
    protected FuzzyDate startDate;
    @XmlElement(name = "end-date")
    protected FuzzyDate endDate;
    @XmlElement(namespace = "http://www.orcid.org/ns/funding", required = true)
    protected Organization organization;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link FundingTitle }
     *     
     */
    public FundingTitle getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingTitle }
     *     
     */
    public void setTitle(FundingTitle value) {
        this.title = value;
    }

    /**
     * Gets the value of the externalIds property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIds }
     *     
     */
    public ExternalIds getExternalIds() {
        return externalIds;
    }

    /**
     * Sets the value of the externalIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIds }
     *     
     */
    public void setExternalIds(ExternalIds value) {
        this.externalIds = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FundingType }
     *     
     */
    public FundingType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingType }
     *     
     */
    public void setType(FundingType value) {
        this.type = value;
    }

    /**
     * Start date for the funding.
     * 
     * @return
     *     possible object is
     *     {@link FuzzyDate }
     *     
     */
    public FuzzyDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuzzyDate }
     *     
     */
    public void setStartDate(FuzzyDate value) {
        this.startDate = value;
    }

    /**
     * End date for the funding.
     * 
     * @return
     *     possible object is
     *     {@link FuzzyDate }
     *     
     */
    public FuzzyDate getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuzzyDate }
     *     
     */
    public void setEndDate(FuzzyDate value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setOrganization(Organization value) {
        this.organization = value;
    }

}
