//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="role">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="reviewer"/>
 *     &lt;enumeration value="editor"/>
 *     &lt;enumeration value="member"/>
 *     &lt;enumeration value="chair"/>
 *     &lt;enumeration value="organizer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "role", namespace = "http://www.orcid.org/ns/peer-review")
@XmlEnum
public enum Role {


    /**
     * 
     * 						A person who formally assess or examines an
     * 						output with a view to
     * 						commenting and evaluating it.
     * 					
     * 
     */
    @XmlEnumValue("reviewer")
    REVIEWER("reviewer"),

    /**
     * A person who coordinates reviews and/or is
     * 						responsible for decision making on the content of a publication.
     * 					
     * 
     */
    @XmlEnumValue("editor")
    EDITOR("editor"),

    /**
     * A person participating in a process, committee or
     * 						activity.
     * 					
     * 
     */
    @XmlEnumValue("member")
    MEMBER("member"),

    /**
     * A person who coordinates reviews and/or is
     * 						responsible for decision making on the content of a conference.
     * 					
     * 
     */
    @XmlEnumValue("chair")
    CHAIR("chair"),

    /**
     * A person who makes arrangements or preparations
     * 						for an event or activity.
     * 					
     * 
     */
    @XmlEnumValue("organizer")
    ORGANIZER("organizer");
    private final String value;

    Role(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Role fromValue(String v) {
        for (Role c: Role.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
