//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package uk.ac.ebi.ddi.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A work published by the researcher or contributor.
 * 					* The visibility attribute (private, limited or public) can be set
 * 					at record creation, and indicates who can see this section of
 * 					information.
 * 					* The put-code attribute is used only when reading this
 * 					element. When updating the item, the put-code attribute must be
 * 					included to indicate the specific record to be updated.
 * 				
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.orcid.org/ns/common}element-summary">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.orcid.org/ns/work}work-title" minOccurs="0"/>
 *         &lt;element name="journal-title" type="{http://www.orcid.org/ns/work}journal-title" minOccurs="0"/>
 *         &lt;element name="short-description" type="{http://www.orcid.org/ns/common}short-description" minOccurs="0"/>
 *         &lt;element name="citation" type="{http://www.orcid.org/ns/work}citation" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.orcid.org/ns/work}work-type"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}publication-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}external-ids" minOccurs="0"/>
 *         &lt;element name="url" type="{http://www.orcid.org/ns/common}url" minOccurs="0"/>
 *         &lt;element name="contributors" type="{http://www.orcid.org/ns/work}work-contributors" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}language-code" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}country" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "journalTitle",
    "shortDescription",
    "citation",
    "type",
    "publicationDate",
    "externalIds",
    "url",
    "contributors",
    "languageCode",
    "country"
})
@XmlRootElement(name = "work", namespace = "http://www.orcid.org/ns/work")
public class Work
    extends ElementSummary
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://www.orcid.org/ns/work")
    protected WorkTitle title;
    @XmlElement(name = "journal-title", namespace = "http://www.orcid.org/ns/work")
    protected String journalTitle;
    @XmlElement(name = "short-description", namespace = "http://www.orcid.org/ns/work")
    protected String shortDescription;
    @XmlElement(namespace = "http://www.orcid.org/ns/work")
    protected Citation citation;
    @XmlElement(namespace = "http://www.orcid.org/ns/work", required = true)
    @XmlSchemaType(name = "string")
    protected WorkType type;
    @XmlElement(name = "publication-date")
    protected FuzzyDate publicationDate;
    @XmlElement(name = "external-ids")
    protected ExternalIds externalIds;
    @XmlElement(namespace = "http://www.orcid.org/ns/work")
    protected Url url;
    @XmlElement(namespace = "http://www.orcid.org/ns/work")
    protected WorkContributors contributors;
    @XmlElement(name = "language-code")
    @XmlSchemaType(name = "string")
    protected LanguageCode languageCode;
    protected Country country;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link WorkTitle }
     *     
     */
    public WorkTitle getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkTitle }
     *     
     */
    public void setTitle(WorkTitle value) {
        this.title = value;
    }

    /**
     * Gets the value of the journalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalTitle() {
        return journalTitle;
    }

    /**
     * Sets the value of the journalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalTitle(String value) {
        this.journalTitle = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link Citation }
     *     
     */
    public Citation getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citation }
     *     
     */
    public void setCitation(Citation value) {
        this.citation = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link WorkType }
     *     
     */
    public WorkType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkType }
     *     
     */
    public void setType(WorkType value) {
        this.type = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link FuzzyDate }
     *     
     */
    public FuzzyDate getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuzzyDate }
     *     
     */
    public void setPublicationDate(FuzzyDate value) {
        this.publicationDate = value;
    }

    /**
     * Element containing the type and content of the
     * 									citation for this work
     * 								
     * 
     * @return
     *     possible object is
     *     {@link ExternalIds }
     *     
     */
    public ExternalIds getExternalIds() {
        return externalIds;
    }

    /**
     * Sets the value of the externalIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIds }
     *     
     */
    public void setExternalIds(ExternalIds value) {
        this.externalIds = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link Url }
     *     
     */
    public Url getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link Url }
     *     
     */
    public void setUrl(Url value) {
        this.url = value;
    }

    /**
     * Gets the value of the contributors property.
     * 
     * @return
     *     possible object is
     *     {@link WorkContributors }
     *     
     */
    public WorkContributors getContributors() {
        return contributors;
    }

    /**
     * Sets the value of the contributors property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkContributors }
     *     
     */
    public void setContributors(WorkContributors value) {
        this.contributors = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageCode }
     *     
     */
    public LanguageCode getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageCode }
     *     
     */
    public void setLanguageCode(LanguageCode value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountry(Country value) {
        this.country = value;
    }

}
