//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credit-name complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="credit-name">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.orcid.org/ns/common>credit-name">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credit-name", namespace = "http://www.orcid.org/ns/personal-details")
@XmlSeeAlso({
    org.europepmc.springframework.social.orcid.jaxb.beans.Name.CreditName.class,
    CreditName2 .class
})
public class CreditName3
    extends org.europepmc.springframework.social.orcid.jaxb.beans.CreditName
    implements Serializable
{

    private final static long serialVersionUID = 1L;

}
