//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * The name to use for the researcher or contributor
 * 				when credited or cited, for example, in an article or index, or as a
 * 				funding contributor. The value of this field also is used as the
 * 				display name for the researcher or contributor in the ORCID Registry
 * 				in their ORCID Record, or when listed as a contributor on other
 * 				ORCID Records. If this element is NULL, given-name family-name will
 * 				be used for display purposes, with a visibility of "public". The
 * 				visibility attribute (private, limited or public) can be set at
 * 				record creation, and indicates who can see this section of
 * 				information.
 * 			
 * 
 * <p>Java class for credit-name complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="credit-name">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.orcid.org/ns/common>string-150">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credit-name", propOrder = {
    "value"
})
@XmlSeeAlso({
    CreditName3 .class
})
public class CreditName
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlValue
    protected String value;

    /**
     * A non-empty string that has a maximum size of 150
     * 				characters
     * 			
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
