//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A simple history of the researcher or
 * 					contributor's
 * 					ORCID Record. The visibility attribute (private, limited or public)
 * 					can be set at record creation, and indicates who can see this
 * 					section of information.
 * 				
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creation-method" type="{http://www.orcid.org/ns/history}creation-method" minOccurs="0"/>
 *         &lt;element name="completion-date" type="{http://www.orcid.org/ns/history}completion-date" minOccurs="0"/>
 *         &lt;element name="submission-date" type="{http://www.orcid.org/ns/history}submission-date" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}last-modified-date" minOccurs="0"/>
 *         &lt;element name="claimed" type="{http://www.orcid.org/ns/history}claimed" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/common}source" minOccurs="0"/>
 *         &lt;element name="deactivation-date" type="{http://www.orcid.org/ns/history}deactivation-date" minOccurs="0"/>
 *         &lt;element name="verified-email" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="verified-primary-email" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="visibility" type="{http://www.orcid.org/ns/common}visibility" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creationMethod",
    "completionDate",
    "submissionDate",
    "lastModifiedDate",
    "claimed",
    "source",
    "deactivationDate",
    "verifiedEmail",
    "verifiedPrimaryEmail"
})
@XmlRootElement(name = "history", namespace = "http://www.orcid.org/ns/history")
public class History
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "creation-method", namespace = "http://www.orcid.org/ns/history")
    @XmlSchemaType(name = "string")
    protected CreationMethod creationMethod;
    @XmlElement(name = "completion-date", namespace = "http://www.orcid.org/ns/history")
    protected CompletionDate completionDate;
    @XmlElement(name = "submission-date", namespace = "http://www.orcid.org/ns/history")
    protected SubmissionDate submissionDate;
    @XmlElement(name = "last-modified-date")
    protected LastModifiedDate lastModifiedDate;
    @XmlElement(namespace = "http://www.orcid.org/ns/history")
    protected Claimed claimed;
    protected Source source;
    @XmlElement(name = "deactivation-date", namespace = "http://www.orcid.org/ns/history")
    protected DeactivationDate deactivationDate;
    @XmlElement(name = "verified-email", namespace = "http://www.orcid.org/ns/history")
    protected boolean verifiedEmail;
    @XmlElement(name = "verified-primary-email", namespace = "http://www.orcid.org/ns/history")
    protected boolean verifiedPrimaryEmail;
    @XmlAttribute(name = "visibility")
    protected Visibility visibility;

    /**
     * Gets the value of the creationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CreationMethod }
     *     
     */
    public CreationMethod getCreationMethod() {
        return creationMethod;
    }

    /**
     * Sets the value of the creationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationMethod }
     *     
     */
    public void setCreationMethod(CreationMethod value) {
        this.creationMethod = value;
    }

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link CompletionDate }
     *     
     */
    public CompletionDate getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompletionDate }
     *     
     */
    public void setCompletionDate(CompletionDate value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link SubmissionDate }
     *     
     */
    public SubmissionDate getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmissionDate }
     *     
     */
    public void setSubmissionDate(SubmissionDate value) {
        this.submissionDate = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link LastModifiedDate }
     *     
     */
    public LastModifiedDate getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastModifiedDate }
     *     
     */
    public void setLastModifiedDate(LastModifiedDate value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the claimed property.
     * 
     * @return
     *     possible object is
     *     {@link Claimed }
     *     
     */
    public Claimed getClaimed() {
        return claimed;
    }

    /**
     * Sets the value of the claimed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Claimed }
     *     
     */
    public void setClaimed(Claimed value) {
        this.claimed = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the deactivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DeactivationDate }
     *     
     */
    public DeactivationDate getDeactivationDate() {
        return deactivationDate;
    }

    /**
     * Sets the value of the deactivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeactivationDate }
     *     
     */
    public void setDeactivationDate(DeactivationDate value) {
        this.deactivationDate = value;
    }

    /**
     * Gets the value of the verifiedEmail property.
     * 
     */
    public boolean isVerifiedEmail() {
        return verifiedEmail;
    }

    /**
     * Sets the value of the verifiedEmail property.
     * 
     */
    public void setVerifiedEmail(boolean value) {
        this.verifiedEmail = value;
    }

    /**
     * Gets the value of the verifiedPrimaryEmail property.
     * 
     */
    public boolean isVerifiedPrimaryEmail() {
        return verifiedPrimaryEmail;
    }

    /**
     * Sets the value of the verifiedPrimaryEmail property.
     * 
     */
    public void setVerifiedPrimaryEmail(boolean value) {
        this.verifiedPrimaryEmail = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Visibility }
     *     
     */
    public Visibility getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Visibility }
     *     
     */
    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

}
