//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.orcid.v2_0.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndDate_QNAME = new QName("http://www.orcid.org/ns/common", "end-date");
    private final static QName _Subtitle_QNAME = new QName("http://www.orcid.org/ns/common", "subtitle");
    private final static QName _GroupOrcidIdentifier_QNAME = new QName("http://www.orcid.org/ns/common", "group-orcid-identifier");
    private final static QName _PublicationDate_QNAME = new QName("http://www.orcid.org/ns/common", "publication-date");
    private final static QName _ExternalId_QNAME = new QName("http://www.orcid.org/ns/common", "external-id");
    private final static QName _ContributorOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "contributor-orcid");
    private final static QName _OrcidId_QNAME = new QName("http://www.orcid.org/ns/common", "orcid-id");
    private final static QName _LanguageCode_QNAME = new QName("http://www.orcid.org/ns/common", "language-code");
    private final static QName _ApplicationGroupOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "application-group-orcid");
    private final static QName _ApplicationOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "application-orcid");
    private final static QName _FuzzyDate_QNAME = new QName("http://www.orcid.org/ns/common", "fuzzy-date");
    private final static QName _StartDate_QNAME = new QName("http://www.orcid.org/ns/common", "start-date");
    private final static QName _SourceOrcid_QNAME = new QName("http://www.orcid.org/ns/common", "source-orcid");
    private final static QName _OrcidIdentifier_QNAME = new QName("http://www.orcid.org/ns/common", "orcid-identifier");
    private final static QName _Title_QNAME = new QName("http://www.orcid.org/ns/common", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.orcid.v2_0.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link FuzzyDate }
     * 
     */
    public FuzzyDate createFuzzyDate() {
        return new FuzzyDate();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link OrcidId }
     * 
     */
    public OrcidId createOrcidId() {
        return new OrcidId();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link CompletionDate }
     * 
     */
    public CompletionDate createCompletionDate() {
        return new CompletionDate();
    }

    /**
     * Create an instance of {@link SubmissionDate }
     * 
     */
    public SubmissionDate createSubmissionDate() {
        return new SubmissionDate();
    }

    /**
     * Create an instance of {@link LastModifiedDate }
     * 
     */
    public LastModifiedDate createLastModifiedDate() {
        return new LastModifiedDate();
    }

    /**
     * Create an instance of {@link Claimed }
     * 
     */
    public Claimed createClaimed() {
        return new Claimed();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link ClientId }
     * 
     */
    public ClientId createClientId() {
        return new ClientId();
    }

    /**
     * Create an instance of {@link SourceName }
     * 
     */
    public SourceName createSourceName() {
        return new SourceName();
    }

    /**
     * Create an instance of {@link DeactivationDate }
     * 
     */
    public DeactivationDate createDeactivationDate() {
        return new DeactivationDate();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link OtherNames }
     * 
     */
    public OtherNames createOtherNames() {
        return new OtherNames();
    }

    /**
     * Create an instance of {@link OtherName }
     * 
     */
    public OtherName createOtherName() {
        return new OtherName();
    }

    /**
     * Create an instance of {@link Biography }
     * 
     */
    public Biography createBiography() {
        return new Biography();
    }

    /**
     * Create an instance of {@link ResearcherUrls }
     * 
     */
    public ResearcherUrls createResearcherUrls() {
        return new ResearcherUrls();
    }

    /**
     * Create an instance of {@link ResearcherUrl }
     * 
     */
    public ResearcherUrl createResearcherUrl() {
        return new ResearcherUrl();
    }

    /**
     * Create an instance of {@link Emails }
     * 
     */
    public Emails createEmails() {
        return new Emails();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link ExternalIdentifiers }
     * 
     */
    public ExternalIdentifiers createExternalIdentifiers() {
        return new ExternalIdentifiers();
    }

    /**
     * Create an instance of {@link ExternalId }
     * 
     */
    public ExternalId createExternalId() {
        return new ExternalId();
    }

    /**
     * Create an instance of {@link ActivitiesSummary }
     * 
     */
    public ActivitiesSummary createActivitiesSummary() {
        return new ActivitiesSummary();
    }

    /**
     * Create an instance of {@link Educations }
     * 
     */
    public Educations createEducations() {
        return new Educations();
    }

    /**
     * Create an instance of {@link Employments }
     * 
     */
    public Employments createEmployments() {
        return new Employments();
    }

    /**
     * Create an instance of {@link Fundings }
     * 
     */
    public Fundings createFundings() {
        return new Fundings();
    }

    /**
     * Create an instance of {@link PeerReviews }
     * 
     */
    public PeerReviews createPeerReviews() {
        return new PeerReviews();
    }

    /**
     * Create an instance of {@link Works }
     * 
     */
    public Works createWorks() {
        return new Works();
    }

    /**
     * Create an instance of {@link Works2 }
     * 
     */
    public Works2 createWorks2() {
        return new Works2();
    }

    /**
     * Create an instance of {@link WorkGroup }
     * 
     */
    public WorkGroup createWorkGroup() {
        return new WorkGroup();
    }

    /**
     * Create an instance of {@link Educations2 }
     * 
     */
    public Educations2 createEducations2() {
        return new Educations2();
    }

    /**
     * Create an instance of {@link EducationSummary }
     * 
     */
    public EducationSummary createEducationSummary() {
        return new EducationSummary();
    }

    /**
     * Create an instance of {@link ElementSummary }
     * 
     */
    public ElementSummary createElementSummary() {
        return new ElementSummary();
    }

    /**
     * Create an instance of {@link CreatedDate }
     * 
     */
    public CreatedDate createCreatedDate() {
        return new CreatedDate();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link PeerReviews2 }
     * 
     */
    public PeerReviews2 createPeerReviews2() {
        return new PeerReviews2();
    }

    /**
     * Create an instance of {@link PeerReviewGroup }
     * 
     */
    public PeerReviewGroup createPeerReviewGroup() {
        return new PeerReviewGroup();
    }

    /**
     * Create an instance of {@link Employments2 }
     * 
     */
    public Employments2 createEmployments2() {
        return new Employments2();
    }

    /**
     * Create an instance of {@link EmploymentSummary }
     * 
     */
    public EmploymentSummary createEmploymentSummary() {
        return new EmploymentSummary();
    }

    /**
     * Create an instance of {@link Fundings2 }
     * 
     */
    public Fundings2 createFundings2() {
        return new Fundings2();
    }

    /**
     * Create an instance of {@link FundingGroup }
     * 
     */
    public FundingGroup createFundingGroup() {
        return new FundingGroup();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link TranslatedTitle }
     * 
     */
    public TranslatedTitle createTranslatedTitle() {
        return new TranslatedTitle();
    }

    /**
     * Create an instance of {@link StringWithLangCode }
     * 
     */
    public StringWithLangCode createStringWithLangCode() {
        return new StringWithLangCode();
    }

    /**
     * Create an instance of {@link SentDate }
     * 
     */
    public SentDate createSentDate() {
        return new SentDate();
    }

    /**
     * Create an instance of {@link ReadDate }
     * 
     */
    public ReadDate createReadDate() {
        return new ReadDate();
    }

    /**
     * Create an instance of {@link ExternalIds }
     * 
     */
    public ExternalIds createExternalIds() {
        return new ExternalIds();
    }

    /**
     * Create an instance of {@link ApprovalDate }
     * 
     */
    public ApprovalDate createApprovalDate() {
        return new ApprovalDate();
    }

    /**
     * Create an instance of {@link ArchivedDate }
     * 
     */
    public ArchivedDate createArchivedDate() {
        return new ArchivedDate();
    }

    /**
     * Create an instance of {@link OrganizationAddress }
     * 
     */
    public OrganizationAddress createOrganizationAddress() {
        return new OrganizationAddress();
    }

    /**
     * Create an instance of {@link ContributorAttributes }
     * 
     */
    public ContributorAttributes createContributorAttributes() {
        return new ContributorAttributes();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link Address2 }
     * 
     */
    public Address2 createAddress2() {
        return new Address2();
    }

    /**
     * Create an instance of {@link ContributorEmail }
     * 
     */
    public ContributorEmail createContributorEmail() {
        return new ContributorEmail();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link uk.ac.ebi.orcid.v2_0.jaxb.beans.CreditName }
     * 
     */
    public org.europepmc.springframework.social.orcid.jaxb.beans.CreditName createCreditName() {
        return new org.europepmc.springframework.social.orcid.jaxb.beans.CreditName();
    }

    /**
     * Create an instance of {@link DisambiguatedOrganization }
     * 
     */
    public DisambiguatedOrganization createDisambiguatedOrganization() {
        return new DisambiguatedOrganization();
    }

    /**
     * Create an instance of {@link Employment }
     * 
     */
    public Employment createEmployment() {
        return new Employment();
    }

    /**
     * Create an instance of {@link Education }
     * 
     */
    public Education createEducation() {
        return new Education();
    }

    /**
     * Create an instance of {@link Funding }
     * 
     */
    public Funding createFunding() {
        return new Funding();
    }

    /**
     * Create an instance of {@link FundingTitle }
     * 
     */
    public FundingTitle createFundingTitle() {
        return new FundingTitle();
    }

    /**
     * Create an instance of {@link Contributors }
     * 
     */
    public Contributors createContributors() {
        return new Contributors();
    }

    /**
     * Create an instance of {@link FundingSummary }
     * 
     */
    public FundingSummary createFundingSummary() {
        return new FundingSummary();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link ContributorAttributes2 }
     * 
     */
    public ContributorAttributes2 createContributorAttributes2() {
        return new ContributorAttributes2();
    }

    /**
     * Create an instance of {@link Work }
     * 
     */
    public Work createWork() {
        return new Work();
    }

    /**
     * Create an instance of {@link WorkTitle }
     * 
     */
    public WorkTitle createWorkTitle() {
        return new WorkTitle();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link WorkContributors }
     * 
     */
    public WorkContributors createWorkContributors() {
        return new WorkContributors();
    }

    /**
     * Create an instance of {@link WorkSummary }
     * 
     */
    public WorkSummary createWorkSummary() {
        return new WorkSummary();
    }

    /**
     * Create an instance of {@link Contributor2 }
     * 
     */
    public Contributor2 createContributor2() {
        return new Contributor2();
    }

    /**
     * Create an instance of {@link ContributorEmail2 }
     * 
     */
    public ContributorEmail2 createContributorEmail2() {
        return new ContributorEmail2();
    }

    /**
     * Create an instance of {@link ContributorAttributes3 }
     * 
     */
    public ContributorAttributes3 createContributorAttributes3() {
        return new ContributorAttributes3();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link PeerReviewSummary }
     * 
     */
    public PeerReviewSummary createPeerReviewSummary() {
        return new PeerReviewSummary();
    }

    /**
     * Create an instance of {@link PeerReview }
     * 
     */
    public PeerReview createPeerReview() {
        return new PeerReview();
    }

    /**
     * Create an instance of {@link CreditName2 }
     * 
     */
    public CreditName2 createCreditName2() {
        return new CreditName2();
    }

    /**
     * Create an instance of {@link CreditName3 }
     * 
     */
    public CreditName3 createCreditName3() {
        return new CreditName3();
    }

    /**
     * Create an instance of {@link PersonalDetails }
     * 
     */
    public PersonalDetails createPersonalDetails() {
        return new PersonalDetails();
    }

    /**
     * Create an instance of {@link Name2 }
     * 
     */
    public Name2 createName2() {
        return new Name2();
    }

    /**
     * Create an instance of {@link Name.GivenNames }
     * 
     */
    public Name.GivenNames createNameGivenNames() {
        return new Name.GivenNames();
    }

    /**
     * Create an instance of {@link Name.FamilyName }
     * 
     */
    public Name.FamilyName createNameFamilyName() {
        return new Name.FamilyName();
    }

    /**
     * Create an instance of {@link Name.CreditName }
     * 
     */
    public Name.CreditName createNameCreditName() {
        return new Name.CreditName();
    }

    /**
     * Create an instance of {@link Biography2 }
     * 
     */
    public Biography2 createBiography2() {
        return new Biography2();
    }

    /**
     * Create an instance of {@link OtherName2 }
     * 
     */
    public OtherName2 createOtherName2() {
        return new OtherName2();
    }

    /**
     * Create an instance of {@link ResearcherUrl2 }
     * 
     */
    public ResearcherUrl2 createResearcherUrl2() {
        return new ResearcherUrl2();
    }

    /**
     * Create an instance of {@link Email2 }
     * 
     */
    public Email2 createEmail2() {
        return new Email2();
    }

    /**
     * Create an instance of {@link Address3 }
     * 
     */
    public Address3 createAddress3() {
        return new Address3();
    }

    /**
     * Create an instance of {@link Keyword2 }
     * 
     */
    public Keyword2 createKeyword2() {
        return new Keyword2();
    }

    /**
     * Create an instance of {@link ExternalIdentifier }
     * 
     */
    public ExternalIdentifier createExternalIdentifier() {
        return new ExternalIdentifier();
    }

    /**
     * Create an instance of {@link SourceReference }
     * 
     */
    public SourceReference createSourceReference() {
        return new SourceReference();
    }

    /**
     * Create an instance of {@link SourceDate }
     * 
     */
    public SourceDate createSourceDate() {
        return new SourceDate();
    }

    /**
     * Create an instance of {@link FuzzyDate.Year }
     * 
     */
    public FuzzyDate.Year createFuzzyDateYear() {
        return new FuzzyDate.Year();
    }

    /**
     * Create an instance of {@link FuzzyDate.Month }
     * 
     */
    public FuzzyDate.Month createFuzzyDateMonth() {
        return new FuzzyDate.Month();
    }

    /**
     * Create an instance of {@link FuzzyDate.Day }
     * 
     */
    public FuzzyDate.Day createFuzzyDateDay() {
        return new FuzzyDate.Day();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "end-date")
    public JAXBElement<FuzzyDate> createEndDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_EndDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "subtitle")
    public JAXBElement<String> createSubtitle(String value) {
        return new JAXBElement<String>(_Subtitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "group-orcid-identifier")
    public JAXBElement<OrcidId> createGroupOrcidIdentifier(OrcidId value) {
        return new JAXBElement<OrcidId>(_GroupOrcidIdentifier_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "publication-date")
    public JAXBElement<FuzzyDate> createPublicationDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_PublicationDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "external-id")
    public JAXBElement<ExternalId> createExternalId(ExternalId value) {
        return new JAXBElement<ExternalId>(_ExternalId_QNAME, ExternalId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "contributor-orcid")
    public JAXBElement<OrcidId> createContributorOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ContributorOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "orcid-id")
    public JAXBElement<OrcidId> createOrcidId(OrcidId value) {
        return new JAXBElement<OrcidId>(_OrcidId_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "language-code")
    public JAXBElement<LanguageCode> createLanguageCode(LanguageCode value) {
        return new JAXBElement<LanguageCode>(_LanguageCode_QNAME, LanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "application-group-orcid")
    public JAXBElement<OrcidId> createApplicationGroupOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ApplicationGroupOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "application-orcid")
    public JAXBElement<OrcidId> createApplicationOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_ApplicationOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "fuzzy-date")
    public JAXBElement<FuzzyDate> createFuzzyDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_FuzzyDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FuzzyDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "start-date")
    public JAXBElement<FuzzyDate> createStartDate(FuzzyDate value) {
        return new JAXBElement<FuzzyDate>(_StartDate_QNAME, FuzzyDate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "source-orcid")
    public JAXBElement<OrcidId> createSourceOrcid(OrcidId value) {
        return new JAXBElement<OrcidId>(_SourceOrcid_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcidId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "orcid-identifier")
    public JAXBElement<OrcidId> createOrcidIdentifier(OrcidId value) {
        return new JAXBElement<OrcidId>(_OrcidIdentifier_QNAME, OrcidId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/common", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

}
