//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.orcid.org/ns/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.europepmc.springframework.social.orcid.jaxb.beans;
