//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.orcid.org/ns/common}element-summary">
 *       &lt;sequence>
 *         &lt;element name="reviewer-role" type="{http://www.orcid.org/ns/peer-review}role"/>
 *         &lt;element name="review-identifiers" type="{http://www.orcid.org/ns/common}external-ids"/>
 *         &lt;element name="review-url" type="{http://www.orcid.org/ns/common}url" minOccurs="0"/>
 *         &lt;element name="review-type" type="{http://www.orcid.org/ns/peer-review}type"/>
 *         &lt;element name="review-completion-date" type="{http://www.orcid.org/ns/common}fuzzy-date"/>
 *         &lt;element name="review-group-id" type="{http://www.orcid.org/ns/common}group-id"/>
 *         &lt;element name="subject-external-identifier" type="{http://www.orcid.org/ns/common}external-id" minOccurs="0"/>
 *         &lt;element name="subject-container-name" type="{http://www.orcid.org/ns/work}journal-title" minOccurs="0"/>
 *         &lt;element name="subject-type" type="{http://www.orcid.org/ns/work}work-type" minOccurs="0"/>
 *         &lt;element name="subject-name" type="{http://www.orcid.org/ns/work}work-title" minOccurs="0"/>
 *         &lt;element name="subject-url" type="{http://www.orcid.org/ns/common}url" minOccurs="0"/>
 *         &lt;element name="convening-organization" type="{http://www.orcid.org/ns/common}organization"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reviewerRole",
    "reviewIdentifiers",
    "reviewUrl",
    "reviewType",
    "reviewCompletionDate",
    "reviewGroupId",
    "subjectExternalIdentifier",
    "subjectContainerName",
    "subjectType",
    "subjectName",
    "subjectUrl",
    "conveningOrganization"
})
@XmlRootElement(name = "peer-review", namespace = "http://www.orcid.org/ns/peer-review")
public class PeerReview
    extends ElementSummary
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "reviewer-role", namespace = "http://www.orcid.org/ns/peer-review", required = true)
    @XmlSchemaType(name = "string")
    protected Role reviewerRole;
    @XmlElement(name = "review-identifiers", namespace = "http://www.orcid.org/ns/peer-review", required = true)
    protected ExternalIds reviewIdentifiers;
    @XmlElement(name = "review-url", namespace = "http://www.orcid.org/ns/peer-review")
    protected Url reviewUrl;
    @XmlElement(name = "review-type", namespace = "http://www.orcid.org/ns/peer-review", required = true)
    @XmlSchemaType(name = "string")
    protected Type reviewType;
    @XmlElement(name = "review-completion-date", namespace = "http://www.orcid.org/ns/peer-review", required = true)
    protected FuzzyDate reviewCompletionDate;
    @XmlElement(name = "review-group-id", namespace = "http://www.orcid.org/ns/peer-review", required = true)
    protected String reviewGroupId;
    @XmlElement(name = "subject-external-identifier", namespace = "http://www.orcid.org/ns/peer-review")
    protected ExternalId subjectExternalIdentifier;
    @XmlElement(name = "subject-container-name", namespace = "http://www.orcid.org/ns/peer-review")
    protected String subjectContainerName;
    @XmlElement(name = "subject-type", namespace = "http://www.orcid.org/ns/peer-review")
    @XmlSchemaType(name = "string")
    protected WorkType subjectType;
    @XmlElement(name = "subject-name", namespace = "http://www.orcid.org/ns/peer-review")
    protected WorkTitle subjectName;
    @XmlElement(name = "subject-url", namespace = "http://www.orcid.org/ns/peer-review")
    protected Url subjectUrl;
    @XmlElement(name = "convening-organization", namespace = "http://www.orcid.org/ns/peer-review", required = true)
    protected Organization conveningOrganization;

    /**
     * Gets the value of the reviewerRole property.
     * 
     * @return
     *     possible object is
     *     {@link Role }
     *     
     */
    public Role getReviewerRole() {
        return reviewerRole;
    }

    /**
     * Sets the value of the reviewerRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link Role }
     *     
     */
    public void setReviewerRole(Role value) {
        this.reviewerRole = value;
    }

    /**
     * Gets the value of the reviewIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalIds }
     *     
     */
    public ExternalIds getReviewIdentifiers() {
        return reviewIdentifiers;
    }

    /**
     * Sets the value of the reviewIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalIds }
     *     
     */
    public void setReviewIdentifiers(ExternalIds value) {
        this.reviewIdentifiers = value;
    }

    /**
     * Gets the value of the reviewUrl property.
     * 
     * @return
     *     possible object is
     *     {@link Url }
     *     
     */
    public Url getReviewUrl() {
        return reviewUrl;
    }

    /**
     * Sets the value of the reviewUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Url }
     *     
     */
    public void setReviewUrl(Url value) {
        this.reviewUrl = value;
    }

    /**
     * Gets the value of the reviewType property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getReviewType() {
        return reviewType;
    }

    /**
     * Sets the value of the reviewType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setReviewType(Type value) {
        this.reviewType = value;
    }

    /**
     * Gets the value of the reviewCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link FuzzyDate }
     *     
     */
    public FuzzyDate getReviewCompletionDate() {
        return reviewCompletionDate;
    }

    /**
     * Sets the value of the reviewCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuzzyDate }
     *     
     */
    public void setReviewCompletionDate(FuzzyDate value) {
        this.reviewCompletionDate = value;
    }

    /**
     * Gets the value of the reviewGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewGroupId() {
        return reviewGroupId;
    }

    /**
     * Sets the value of the reviewGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewGroupId(String value) {
        this.reviewGroupId = value;
    }

    /**
     * Gets the value of the subjectExternalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalId }
     *     
     */
    public ExternalId getSubjectExternalIdentifier() {
        return subjectExternalIdentifier;
    }

    /**
     * Sets the value of the subjectExternalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalId }
     *     
     */
    public void setSubjectExternalIdentifier(ExternalId value) {
        this.subjectExternalIdentifier = value;
    }

    /**
     * Gets the value of the subjectContainerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectContainerName() {
        return subjectContainerName;
    }

    /**
     * Sets the value of the subjectContainerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectContainerName(String value) {
        this.subjectContainerName = value;
    }

    /**
     * Gets the value of the subjectType property.
     * 
     * @return
     *     possible object is
     *     {@link WorkType }
     *     
     */
    public WorkType getSubjectType() {
        return subjectType;
    }

    /**
     * Sets the value of the subjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkType }
     *     
     */
    public void setSubjectType(WorkType value) {
        this.subjectType = value;
    }

    /**
     * Gets the value of the subjectName property.
     * 
     * @return
     *     possible object is
     *     {@link WorkTitle }
     *     
     */
    public WorkTitle getSubjectName() {
        return subjectName;
    }

    /**
     * Sets the value of the subjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkTitle }
     *     
     */
    public void setSubjectName(WorkTitle value) {
        this.subjectName = value;
    }

    /**
     * Gets the value of the subjectUrl property.
     * 
     * @return
     *     possible object is
     *     {@link Url }
     *     
     */
    public Url getSubjectUrl() {
        return subjectUrl;
    }

    /**
     * Sets the value of the subjectUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Url }
     *     
     */
    public void setSubjectUrl(Url value) {
        this.subjectUrl = value;
    }

    /**
     * Gets the value of the conveningOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getConveningOrganization() {
        return conveningOrganization;
    }

    /**
     * Sets the value of the conveningOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setConveningOrganization(Organization value) {
        this.conveningOrganization = value;
    }

}
