//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The container element for a researcher or
 * 					contributor ORCID Record.
 * 					* The type attribute can only be set by
 * 					ORCID, and indicates the type of ORCID Record the information
 * 					refers
 * 					to. In most cases the value will be "user" to indicate an
 * 					ORCID iD
 * 					holder.
 * 					* The client type attribute is set by ORCID, and is
 * 					present
 * 					when the type attribute is "group" or "client". This
 * 					attribute
 * 					indicates the API privileges held by the group as
 * 					indicated by
 * 					their
 * 					ORCID Membership Agreement.
 * 				
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/common}orcid-identifier" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/preferences}preferences" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/history}history" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/person}person" minOccurs="0"/>
 *         &lt;element ref="{http://www.orcid.org/ns/activities}activities-summary" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="path" type="{http://www.orcid.org/ns/common}element-path" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orcidIdentifier",
    "preferences",
    "history",
    "person",
    "activitiesSummary"
})
@XmlRootElement(name = "record", namespace = "http://www.orcid.org/ns/record")
public class Record
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "orcid-identifier")
    protected OrcidId orcidIdentifier;
    @XmlElement(namespace = "http://www.orcid.org/ns/preferences")
    protected Preferences preferences;
    @XmlElement(namespace = "http://www.orcid.org/ns/history")
    protected History history;
    @XmlElement(namespace = "http://www.orcid.org/ns/person")
    protected Person person;
    @XmlElement(name = "activities-summary", namespace = "http://www.orcid.org/ns/activities")
    protected ActivitiesSummary activitiesSummary;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * Gets the value of the orcidIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    public OrcidId getOrcidIdentifier() {
        return orcidIdentifier;
    }

    /**
     * Sets the value of the orcidIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    public void setOrcidIdentifier(OrcidId value) {
        this.orcidIdentifier = value;
    }

    /**
     * Gets the value of the preferences property.
     * 
     * @return
     *     possible object is
     *     {@link Preferences }
     *     
     */
    public Preferences getPreferences() {
        return preferences;
    }

    /**
     * Sets the value of the preferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preferences }
     *     
     */
    public void setPreferences(Preferences value) {
        this.preferences = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
    public History getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
    public void setHistory(History value) {
        this.history = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the activitiesSummary property.
     * 
     * @return
     *     possible object is
     *     {@link ActivitiesSummary }
     *     
     */
    public ActivitiesSummary getActivitiesSummary() {
        return activitiesSummary;
    }

    /**
     * Sets the value of the activitiesSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivitiesSummary }
     *     
     */
    public void setActivitiesSummary(ActivitiesSummary value) {
        this.activitiesSummary = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
