//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The client application (Member organization's
 * 				system) or user that created the item. XSD VERSION 1.2 UPDATE: the
 * 				identifier for the source may be either an ORCID iD (representing
 * 				individuals and legacy client applications) or a Client ID
 * 				(representing all newer client applications)
 * 			
 * 
 * <p>Java class for source-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="source-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.orcid.org/ns/common}source-orcid"/>
 *           &lt;element name="source-client-id" type="{http://www.orcid.org/ns/common}client-id"/>
 *         &lt;/choice>
 *         &lt;element name="source-name" type="{http://www.orcid.org/ns/common}source-name" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "source-type", propOrder = {
    "sourceClientId",
    "sourceOrcid",
    "sourceName"
})
@XmlRootElement(name = "source")
public class Source
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "source-client-id")
    protected ClientId sourceClientId;
    @XmlElement(name = "source-orcid")
    protected OrcidId sourceOrcid;
    @XmlElement(name = "source-name")
    protected SourceName sourceName;

    /**
     * Gets the value of the sourceClientId property.
     * 
     * @return
     *     possible object is
     *     {@link ClientId }
     *     
     */
    public ClientId getSourceClientId() {
        return sourceClientId;
    }

    /**
     * Sets the value of the sourceClientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientId }
     *     
     */
    public void setSourceClientId(ClientId value) {
        this.sourceClientId = value;
    }

    /**
     * The ORCID identifier for the individual user (or
     * 							legacy client application) that created the item. For identifiers
     * 							of
     * 							individual users, it may be used to look up ORCID record
     * 							details via
     * 							the API.
     * 						
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    public OrcidId getSourceOrcid() {
        return sourceOrcid;
    }

    /**
     * Sets the value of the sourceOrcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    public void setSourceOrcid(OrcidId value) {
        this.sourceOrcid = value;
    }

    /**
     * Gets the value of the sourceName property.
     * 
     * @return
     *     possible object is
     *     {@link SourceName }
     *     
     */
    public SourceName getSourceName() {
        return sourceName;
    }

    /**
     * Sets the value of the sourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceName }
     *     
     */
    public void setSourceName(SourceName value) {
        this.sourceName = value;
    }

}
