//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 11:16:50 AM BST 
//


package org.europepmc.springframework.social.orcid.jaxb.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for work-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="work-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="artistic-performance"/>
 *     &lt;enumeration value="book-chapter"/>
 *     &lt;enumeration value="book-review"/>
 *     &lt;enumeration value="book"/>
 *     &lt;enumeration value="conference-abstract"/>
 *     &lt;enumeration value="conference-paper"/>
 *     &lt;enumeration value="conference-poster"/>
 *     &lt;enumeration value="data-set"/>
 *     &lt;enumeration value="dictionary-entry"/>
 *     &lt;enumeration value="disclosure"/>
 *     &lt;enumeration value="dissertation"/>
 *     &lt;enumeration value="edited-book"/>
 *     &lt;enumeration value="encyclopedia-entry"/>
 *     &lt;enumeration value="invention"/>
 *     &lt;enumeration value="journal-article"/>
 *     &lt;enumeration value="journal-issue"/>
 *     &lt;enumeration value="lecture-speech"/>
 *     &lt;enumeration value="license"/>
 *     &lt;enumeration value="magazine-article"/>
 *     &lt;enumeration value="manual"/>
 *     &lt;enumeration value="newsletter-article"/>
 *     &lt;enumeration value="newspaper-article"/>
 *     &lt;enumeration value="online-resource"/>
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="patent"/>
 *     &lt;enumeration value="registered-copyright"/>
 *     &lt;enumeration value="report"/>
 *     &lt;enumeration value="research-technique"/>
 *     &lt;enumeration value="research-tool"/>
 *     &lt;enumeration value="spin-off-company"/>
 *     &lt;enumeration value="standards-and-policy"/>
 *     &lt;enumeration value="supervised-student-publication"/>
 *     &lt;enumeration value="technical-standard"/>
 *     &lt;enumeration value="test"/>
 *     &lt;enumeration value="translation"/>
 *     &lt;enumeration value="trademark"/>
 *     &lt;enumeration value="website"/>
 *     &lt;enumeration value="working-paper"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "work-type", namespace = "http://www.orcid.org/ns/work")
@XmlEnum
public enum WorkType {

    @XmlEnumValue("artistic-performance")
    ARTISTIC_PERFORMANCE("artistic-performance"),
    @XmlEnumValue("book-chapter")
    BOOK_CHAPTER("book-chapter"),
    @XmlEnumValue("book-review")
    BOOK_REVIEW("book-review"),
    @XmlEnumValue("book")
    BOOK("book"),
    @XmlEnumValue("conference-abstract")
    CONFERENCE_ABSTRACT("conference-abstract"),
    @XmlEnumValue("conference-paper")
    CONFERENCE_PAPER("conference-paper"),
    @XmlEnumValue("conference-poster")
    CONFERENCE_POSTER("conference-poster"),
    @XmlEnumValue("data-set")
    DATA_SET("data-set"),
    @XmlEnumValue("dictionary-entry")
    DICTIONARY_ENTRY("dictionary-entry"),
    @XmlEnumValue("disclosure")
    DISCLOSURE("disclosure"),
    @XmlEnumValue("dissertation")
    DISSERTATION("dissertation"),
    @XmlEnumValue("edited-book")
    EDITED_BOOK("edited-book"),
    @XmlEnumValue("encyclopedia-entry")
    ENCYCLOPEDIA_ENTRY("encyclopedia-entry"),
    @XmlEnumValue("invention")
    INVENTION("invention"),
    @XmlEnumValue("journal-article")
    JOURNAL_ARTICLE("journal-article"),
    @XmlEnumValue("journal-issue")
    JOURNAL_ISSUE("journal-issue"),
    @XmlEnumValue("lecture-speech")
    LECTURE_SPEECH("lecture-speech"),
    @XmlEnumValue("license")
    LICENSE("license"),
    @XmlEnumValue("magazine-article")
    MAGAZINE_ARTICLE("magazine-article"),
    @XmlEnumValue("manual")
    MANUAL("manual"),
    @XmlEnumValue("newsletter-article")
    NEWSLETTER_ARTICLE("newsletter-article"),
    @XmlEnumValue("newspaper-article")
    NEWSPAPER_ARTICLE("newspaper-article"),
    @XmlEnumValue("online-resource")
    ONLINE_RESOURCE("online-resource"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("patent")
    PATENT("patent"),
    @XmlEnumValue("registered-copyright")
    REGISTERED_COPYRIGHT("registered-copyright"),
    @XmlEnumValue("report")
    REPORT("report"),
    @XmlEnumValue("research-technique")
    RESEARCH_TECHNIQUE("research-technique"),
    @XmlEnumValue("research-tool")
    RESEARCH_TOOL("research-tool"),
    @XmlEnumValue("spin-off-company")
    SPIN_OFF_COMPANY("spin-off-company"),
    @XmlEnumValue("standards-and-policy")
    STANDARDS_AND_POLICY("standards-and-policy"),
    @XmlEnumValue("supervised-student-publication")
    SUPERVISED_STUDENT_PUBLICATION("supervised-student-publication"),
    @XmlEnumValue("technical-standard")
    TECHNICAL_STANDARD("technical-standard"),
    @XmlEnumValue("test")
    TEST("test"),
    @XmlEnumValue("translation")
    TRANSLATION("translation"),
    @XmlEnumValue("trademark")
    TRADEMARK("trademark"),
    @XmlEnumValue("website")
    WEBSITE("website"),
    @XmlEnumValue("working-paper")
    WORKING_PAPER("working-paper");
    private final String value;

    WorkType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WorkType fromValue(String v) {
        for (WorkType c: WorkType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
